[build]
  command = "vite build"
  publish = "dist"

[[redirects]]
  from = "/favicon.ico"
  to = "https://coworking-metz/favicon/favicon.ico"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
